services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - db
    user: "${DOCKER_EXEC_USER:-root}"
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - .:/app
      - ../res:/res
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    restart: always
    user: root
volumes:
  bundle_data:
  postgres:
